---
trigger: 
  - master

pool: Pipeline

stages:
  - stage: 'imagebuild'
    jobs:
      - job: 'create container'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: Python
              repository: src
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              buildContext: '**'
              tags: '$(Build.BuildId)'
