---
trigger: 
  - master

stages:
  - stage: 'imagebuild_1'
    jobs:
      - job: 'createcontainer'
        pool:
          name: Pipeline
          demands: 
            - Agent.Name -equals King
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: Python
              repository: src
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              buildContext: '**'
              tags: '$(Build.BuildId)'
  - stage: 'k8s_cluster'
    jobs:
      - job: 'containerdeploy'
        pool:
          name: Pipeline
          demands: 
            - Agent.Name -equals Queen
        steps: 
          - task: Kubernetes@1
            inputs: 
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: k8s
              useClusterAdmin: false
              command: 'apply'
              useConfigurationFile: true
              configurationType: 'configuration'
              configuration: ./k8s.yml